### ISSUE TITLE
Multiple Interfaces on Modular Head Node

### ISSUE THREAD

**Issue by brrueckerc** [OpenAutomationTechnologies/openCONFIGURATOR_eclipse_plugin#26]
The handling of multiple interfaces with the same module type does not work properly in openCONFIGURATOR. Please find the attached XDDs which highlight the problem. 

[ModularDeviceXDD.zip](https://github.com/OpenAutomationTechnologies/openCONFIGURATOR_eclipse_plugin/files/1781549/ModularDeviceXDD.zip)

**Comment by powerlink-team-kalycito** [comment]
Pull request #29 (Pull request is merged) resolves this issue. Hence this issue can be closed.
